version: "3.1"

services:
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mabite
      MYSQL_DATABASE: blog
      MYSQL_USER: adm
      MYSQL_PASSWORD: mabite
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - 8090:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: mabite